# Librerías

In [1]:
import pandas as pd

# Dataset

In [2]:
df = pd.read_csv("Data/dataset_migracion_venezolana.csv")

In [3]:
df

,Unnamed: 0,Titulo,URL,Cuerpo,Autor,Medio,Pais,Fecha
0,0,"Dane señala que pobreza en Colombia bajó, pero...",https://www.semana.com/economia/macroeconomia/...,El Departamento Administrativo Nacional de Est...,Manuel Santiago Sánchez González,Semana,Colombia,"Sep 15, 2026"
1,1,Denuncian detención de un periodista nicaragüe...,https://www.semana.com/mundo/articulo/denuncia...,"El periodista nicaragüense Luis Galeano, direc...",Juan David Cardozo Maglioni,Semana,Colombia,"Sep 14, 2026"
2,2,Vuelven los vuelos de deportación a Venezuela:...,https://www.semana.com/mundo/articulo/vuelven-...,Estados Unidos reanudó este lunes los vuelos d...,Juan Felipe Useche Chacón,Semana,Colombia,"Aug 04, 2026"
3,3,Venezolanos se unen por Colombia tras terremot...,https://www.semana.com/nacion/articulo/venezol...,La solidaridad de los venezolanos por el terre...,Gabriel Salazar López,Semana,Colombia,"Aug 12, 2026"
4,4,"Panamá enviará, por primera vez, un avión dire...",https://www.semana.com/mundo/articulo/panama-e...,"Panamá enviará, por primera vez, un vuelo dire...",Juan David Cardozo Maglioni,Semana,Colombia,"Dec 18, 2025"
...,...,...,...,...,...,...,...,...
155,155,EU extiende amparo migratorio para migrantes v...,https://www.milenio.com/internacional/estados-...,El gobierno del presidente estadunidense Joe B...,AFP,Milenio,México,2022-07-11 20:06
156,156,Sale caravana de migrantes venezolanos desde T...,https://www.milenio.com/estados/caravana-migra...,"Una caravana de migrantes, en su mayoría venez...",Julio Navarro Cárdenas,Milenio,México,2022-06-24 13:56
157,157,"Entre calor y fatiga, migrantes quedan varados...",https://www.milenio.com/politica/migrantes-olv...,Suscríbete a Milenio y descarga la edición imp...,Redacción,Milenio,México,2022-06-17 15:37
158,158,"""Plan Vuelta a la Patria"": Maduro promete trip...",https://www.milenio.com/internacional/plan-vue...,"El presidente de Venezuela, Nicolás Maduro, pr...",Editorial Milenio,Milenio,México,2022-02-02 19:47
159,159,EU envía a Colombia a migrantes venezolanos de...,https://www.milenio.com/internacional/eu-envia...,El gobierno de Estados Unidos informó el lunes...,AFP,Milenio,México,2022-01-31 19:48

# EDA

In [4]:
df.shape

(160, 8)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  160 non-null    int64
 1   Titulo      160 non-null    str
 2   URL         160 non-null    str
 3   Cuerpo      159 non-null    str
 4   Autor       160 non-null    str
 5   Medio       160 non-null    str
 6   Pais        160 non-null    str
 7   Fecha       160 non-null    str
dtypes: int64(1), str(7)
memory usage: 10.1 KB

In [6]:

# Eliminar la primera columna (la columna de ID actual sin título)
df = df.iloc[:, 1:]

# Crear la nueva columna ID
df.insert(
    0,  # posición (primera columna)
    "ID",
    [f"articulo_{i}" for i in range(1, len(df) + 1)]
)

In [7]:
df

,ID,Titulo,URL,Cuerpo,Autor,Medio,Pais,Fecha
0,articulo_1,"Dane señala que pobreza en Colombia bajó, pero...",https://www.semana.com/economia/macroeconomia/...,El Departamento Administrativo Nacional de Est...,Manuel Santiago Sánchez González,Semana,Colombia,"Sep 15, 2026"
1,articulo_2,Denuncian detención de un periodista nicaragüe...,https://www.semana.com/mundo/articulo/denuncia...,"El periodista nicaragüense Luis Galeano, direc...",Juan David Cardozo Maglioni,Semana,Colombia,"Sep 14, 2026"
2,articulo_3,Vuelven los vuelos de deportación a Venezuela:...,https://www.semana.com/mundo/articulo/vuelven-...,Estados Unidos reanudó este lunes los vuelos d...,Juan Felipe Useche Chacón,Semana,Colombia,"Aug 04, 2026"
3,articulo_4,Venezolanos se unen por Colombia tras terremot...,https://www.semana.com/nacion/articulo/venezol...,La solidaridad de los venezolanos por el terre...,Gabriel Salazar López,Semana,Colombia,"Aug 12, 2026"
4,articulo_5,"Panamá enviará, por primera vez, un avión dire...",https://www.semana.com/mundo/articulo/panama-e...,"Panamá enviará, por primera vez, un vuelo dire...",Juan David Cardozo Maglioni,Semana,Colombia,"Dec 18, 2025"
...,...,...,...,...,...,...,...,...
155,articulo_156,EU extiende amparo migratorio para migrantes v...,https://www.milenio.com/internacional/estados-...,El gobierno del presidente estadunidense Joe B...,AFP,Milenio,México,2022-07-11 20:06
156,articulo_157,Sale caravana de migrantes venezolanos desde T...,https://www.milenio.com/estados/caravana-migra...,"Una caravana de migrantes, en su mayoría venez...",Julio Navarro Cárdenas,Milenio,México,2022-06-24 13:56
157,articulo_158,"Entre calor y fatiga, migrantes quedan varados...",https://www.milenio.com/politica/migrantes-olv...,Suscríbete a Milenio y descarga la edición imp...,Redacción,Milenio,México,2022-06-17 15:37
158,articulo_159,"""Plan Vuelta a la Patria"": Maduro promete trip...",https://www.milenio.com/internacional/plan-vue...,"El presidente de Venezuela, Nicolás Maduro, pr...",Editorial Milenio,Milenio,México,2022-02-02 19:47
159,articulo_160,EU envía a Colombia a migrantes venezolanos de...,https://www.milenio.com/internacional/eu-envia...,El gobierno de Estados Unidos informó el lunes...,AFP,Milenio,México,2022-01-31 19:48

Debemos estandarizar las fechas y anonimizar a los autores:

#### Estandarización de las fechas

In [8]:
df["Fecha"] = pd.to_datetime(
    df["Fecha"],
    format="mixed",   # útil para formatos distintos
    errors="coerce"
)

df["Fecha"] = df["Fecha"].dt.strftime("%Y-%m-%d")

In [9]:
df

,ID,Titulo,URL,Cuerpo,Autor,Medio,Pais,Fecha
0,articulo_1,"Dane señala que pobreza en Colombia bajó, pero...",https://www.semana.com/economia/macroeconomia/...,El Departamento Administrativo Nacional de Est...,Manuel Santiago Sánchez González,Semana,Colombia,2026-09-15
1,articulo_2,Denuncian detención de un periodista nicaragüe...,https://www.semana.com/mundo/articulo/denuncia...,"El periodista nicaragüense Luis Galeano, direc...",Juan David Cardozo Maglioni,Semana,Colombia,2026-09-14
2,articulo_3,Vuelven los vuelos de deportación a Venezuela:...,https://www.semana.com/mundo/articulo/vuelven-...,Estados Unidos reanudó este lunes los vuelos d...,Juan Felipe Useche Chacón,Semana,Colombia,2026-08-04
3,articulo_4,Venezolanos se unen por Colombia tras terremot...,https://www.semana.com/nacion/articulo/venezol...,La solidaridad de los venezolanos por el terre...,Gabriel Salazar López,Semana,Colombia,2026-08-12
4,articulo_5,"Panamá enviará, por primera vez, un avión dire...",https://www.semana.com/mundo/articulo/panama-e...,"Panamá enviará, por primera vez, un vuelo dire...",Juan David Cardozo Maglioni,Semana,Colombia,2025-12-18
...,...,...,...,...,...,...,...,...
155,articulo_156,EU extiende amparo migratorio para migrantes v...,https://www.milenio.com/internacional/estados-...,El gobierno del presidente estadunidense Joe B...,AFP,Milenio,México,2022-07-11
156,articulo_157,Sale caravana de migrantes venezolanos desde T...,https://www.milenio.com/estados/caravana-migra...,"Una caravana de migrantes, en su mayoría venez...",Julio Navarro Cárdenas,Milenio,México,2022-06-24
157,articulo_158,"Entre calor y fatiga, migrantes quedan varados...",https://www.milenio.com/politica/migrantes-olv...,Suscríbete a Milenio y descarga la edición imp...,Redacción,Milenio,México,2022-06-17
158,articulo_159,"""Plan Vuelta a la Patria"": Maduro promete trip...",https://www.milenio.com/internacional/plan-vue...,"El presidente de Venezuela, Nicolás Maduro, pr...",Editorial Milenio,Milenio,México,2022-02-02
159,articulo_160,EU envía a Colombia a migrantes venezolanos de...,https://www.milenio.com/internacional/eu-envia...,El gobierno de Estados Unidos informó el lunes...,AFP,Milenio,México,2022-01-31

#### Anonimización de los autores

In [10]:
autores_unicos = df["Autor"].unique()

In [11]:
df_autores = pd.DataFrame({
    "ID_Autor": [f"AutorID_{i}" for i in range(1, len(autores_unicos) + 1)],
    "Autor": autores_unicos
}
)

In [12]:
df_autores.to_csv(
    "Data/dataset_autores_anonimizados.csv",
    index = False,
    encoding= "utf-8-sig"
)

df_autores

      ID_Autor                             Autor
0    AutorID_1  Manuel Santiago Sánchez González
1    AutorID_2       Juan David Cardozo Maglioni
2    AutorID_3         Juan Felipe Useche Chacón
3    AutorID_4             Gabriel Salazar López
4    AutorID_5            Deivis Ramírez Miranda
..         ...                               ...
87  AutorID_88                   César Velázquez
88  AutorID_89                   Milenio Digital
89  AutorID_90                 Editorial Milenio
90  AutorID_91                    Jaime Zambrano
91  AutorID_92              Jesús Alberto García

[92 rows x 2 columns]

In [13]:
# Crear diccionario Autor -> AutorID
mapa_autores = dict(zip(df_autores["Autor"], df_autores["ID_Autor"]))

# Reemplazar nombres por IDs
df["Autor"] = df["Autor"].map(mapa_autores)

In [14]:
df

,ID,Titulo,URL,Cuerpo,Autor,Medio,Pais,Fecha
0,articulo_1,"Dane señala que pobreza en Colombia bajó, pero...",https://www.semana.com/economia/macroeconomia/...,El Departamento Administrativo Nacional de Est...,AutorID_1,Semana,Colombia,2026-09-15
1,articulo_2,Denuncian detención de un periodista nicaragüe...,https://www.semana.com/mundo/articulo/denuncia...,"El periodista nicaragüense Luis Galeano, direc...",AutorID_2,Semana,Colombia,2026-09-14
2,articulo_3,Vuelven los vuelos de deportación a Venezuela:...,https://www.semana.com/mundo/articulo/vuelven-...,Estados Unidos reanudó este lunes los vuelos d...,AutorID_3,Semana,Colombia,2026-08-04
3,articulo_4,Venezolanos se unen por Colombia tras terremot...,https://www.semana.com/nacion/articulo/venezol...,La solidaridad de los venezolanos por el terre...,AutorID_4,Semana,Colombia,2026-08-12
4,articulo_5,"Panamá enviará, por primera vez, un avión dire...",https://www.semana.com/mundo/articulo/panama-e...,"Panamá enviará, por primera vez, un vuelo dire...",AutorID_2,Semana,Colombia,2025-12-18
...,...,...,...,...,...,...,...,...
155,articulo_156,EU extiende amparo migratorio para migrantes v...,https://www.milenio.com/internacional/estados-...,El gobierno del presidente estadunidense Joe B...,AutorID_71,Milenio,México,2022-07-11
156,articulo_157,Sale caravana de migrantes venezolanos desde T...,https://www.milenio.com/estados/caravana-migra...,"Una caravana de migrantes, en su mayoría venez...",AutorID_83,Milenio,México,2022-06-24
157,articulo_158,"Entre calor y fatiga, migrantes quedan varados...",https://www.milenio.com/politica/migrantes-olv...,Suscríbete a Milenio y descarga la edición imp...,AutorID_63,Milenio,México,2022-06-17
158,articulo_159,"""Plan Vuelta a la Patria"": Maduro promete trip...",https://www.milenio.com/internacional/plan-vue...,"El presidente de Venezuela, Nicolás Maduro, pr...",AutorID_90,Milenio,México,2022-02-02
159,articulo_160,EU envía a Colombia a migrantes venezolanos de...,https://www.milenio.com/internacional/eu-envia...,El gobierno de Estados Unidos informó el lunes...,AutorID_71,Milenio,México,2022-01-31

In [15]:
df.to_csv(
    
    "Data/dataset_migracion_venezolana_limpio_estandarizado.csv",
    index = False,
    encoding="utf-8-sig"

)